### ISSUE TITLE
Is "Historical" redundant in the type names?

### ISSUE THREAD

**Issue by stoicflame** [historical-data/schema#22]
I thought I'd open up a thread to get people's opinions on whether the "Historical" label is redundant in HistoricalPerson, HistoricalEvent, HistoricalFamily, etc. I guess I can appreciate that it's useful to quickly distinguish the "Person" being defined in this schema from the "Person" defined in the root namespace, but isn't that what namespacing is for?

Anyway, I don't feel too strongly about it, but my preference would be to simplify the references to these types by removing the "Historical" from the name and to distinguish it by the namespace.

Thoughts?

**Comment by RobertGardner** [comment]
Seems to me that HistoricalPerson is much more clearly different than Person than is "Person but in the historical-data.org namespace". Also, for non-schema.org-aware apps the distinctly different name makes it easier to distinguish which sites are genealogy-related vs., say, social. This is, though, a minor argument because one could search for historical-data.org rather than HistoricalPerson.

I find the more explicit name more clear. That's my opinion.

**Comment by davebarney** [comment]
I agree that HistoricalPerson is more explicit and clear and would prefer keeping it that way. I don't really see any disadvantage to the longer, more explicit names, but can think of some for shortening them.

**Comment by ninjudd** [comment]
There is some appeal to getting rid of the duplication and going with `http://historical-data.org/Person`. We initially used `HistoricalPerson` because there was an off chance that our schema would be included in `http://schema.org`. But the shorter version is more difficult for people to parse when reading source directly.

I'd say my preference would be to shorten it. Seems more parsimonious... But I don't feel too strongly about it either.

**Comment by davebarney** [comment]
I think including this in schema.org remains a goal and potential outcome, which argues for keeping the longer names. The Schema.org team is very open to including what we come up with and once adopted by multiple content providers in industry is a probably outcome.
