### ISSUE TITLE
Other religions

### ISSUE THREAD

**Issue by domguard** [historical-data/schema#35]
Does the christening property means that this schema only applies to catholic/protestant countries data ?
What if I have buddhist, muslim ancesters to describe in my familiy tree ?

**Comment by danbri** [comment]
My understanding (from brief discussion of this on a call w/ the schema.org team) was that
- there is a lot of available-to-publish geneological data that records this information, so it seems reasonable to create a way to represent it
- in cases where it isn't applicable, it isn't used
- the schema design is intended to be universally applicable, even if it contains pragmatic properties of more limited use, like this one
- we're always open to suggestions for useful additions that improve coverage and cultural diversity

Looking at http://en.wikipedia.org/wiki/Baptism and http://en.wikipedia.org/wiki/Infant_baptism the applicability seems more complex than "catholic/protestant", btw. From that latter page:

"Most Christians belong to denominations that practise infant baptism.[3] Denominations that practise infant baptism include the Roman Catholic Church, the Eastern Orthodox Church, Oriental Orthodoxy, Armenian Apostolic Church, Assyrian Church of the East, the Anglican churches, Lutherans, Presbyterians, Methodists, some Church of the Nazarene,[4] the Reformed Church in America,[5] the United Church of Canada, the United Church of Christ (UCC), and the Continental Reformed.

Groups within the Protestant tradition that reject infant baptism include the Baptists, Apostolic Christians, Disciples of Christ and the Churches of Christ, most Pentecostals, Mennonites, Amish, Plymouth Brethren, Seventh-day Adventists, most non-denominational churches, and otherArminian denominations. Infant baptism is also excluded by Iglesia ni Cristo (Church of Christ), Jehovah's Witnesses, Christadelphians, and Latter Day Saints."

I also read "In some traditions, baptism is also called christening, but for others the word "christening" is reserved for the baptism of infants."

More questions -

In family history data, is it fair to assume the 'christening' property relates almost always to infant baptism records, rather than e.g. adult admission into a religious group? 

Are there substantial bodies of recorded data for similar properties in other religious/cultural traditions? If so, are there obvious or candidate property names that would cover these cases too? e.g. a more neutral terms that covers both, or new per-tradition terms?

**Comment by domguard** [comment]
Catholic/protestant was a shortcut, from the list you bring, I think we can agree the term applies  to [judeo-christian](http://en.wikipedia.org/wiki/Judeo-Christian) religions.

To answer your last question [yes](http://en.wikipedia.org/wiki/Category:Muslim_family_trees), [undoubtly](http://en.wikipedia.org/wiki/Family_tree_of_Confucius_in_the_main_line_of_descent), if we look for genealogical data from other parts of the judeo-christian world we'll find some.
The fact that scholars or inhabitants from these countries are not actually using the web to store their genealogical data does not mean they won't start doing it in the future. 
And by defining standards which can embrace others cultures concepts, we may creates an incentive for these people to use them : if the wider adoption of standards is not their inner goal, I must have missed something.

[This kind of issues is not new](http://www.w3.org/International/questions/qa-personal-names) as we move towards a real global web, that's why I tend to react quickly each time I detect some kind of occident-centric approach in web standards.

But then, I'm not into genealogy right now, have no immediate need for the historical-data extensions nor time to contribute the effort, so feel free to close this issue if you think it's pointless.

**Comment by DallanQ** [comment]
Many genealogy programs list birth, christening, death, and burial as the four major personal events, and list all other events in a separate area. I think it's because it's semi-frequently the case that people don't know an exact birth date and only have access to the christening date in the parish register, so christening is used as a proxy for birth, and likewise burial is used as a proxy for death.  Searches can take advantage of this, and index the christening date when the birth date is unknown.  I don't think we can have much influence on how people label events, but labeling adult admission into a religious order as "christening" would detract from using christening as a proxy for birth in these cases, so it would be nice if we could recommend against that.

BTW, at WeRelate I've had users request that "baptism" also be used as a proxy for birth in search when birth and christening are empty (see http://www.werelate.org/wiki/WeRelate_talk:Watercooler/Archive_2007#Baptism_on_person_pages and
http://www.werelate.org/wiki/WeRelate_talk:Watercooler/Archive_2011#Baptism_.2F_burial_as_proxy_for_birth_.2F_death_in_search_results_.5B11_April_2011.5D ) under the idea that if the parish register says "baptism", people want to record it as a "baptism" and not "christening".  So at WeRelate, both christening and baptism are used as proxies for birth in search.

Having said this, I'm not recommending that baptism be added as one of the four major events, or that we replace christening with a term that encompasses both baptism and christening.  Highlighting birth, christening, death, and burial as the four major personal events is pretty common, and I don't think we need to change that.  If anything, rather than try to highlight additional types of events, baptism and any other birth-like events could simply be listed as additional events.

**Comment by RobertGardner** [comment]
Agreed with DallanQ. We did have extensive discussion on this property and are very sensitive to it being a judeo-christian term. However, since frequently the birth date is not known but the christening date is, we felt it needed to be included. Given that, if there are other common terms in use in other religions/areas are often a proxy for birth date, we would be most happy to either change this one or add those.

Another alternative would be to change the definition of birth date to include christening, making it more clear that it is the birth date we are trying to capture, not the date a person joined a specific religion. If we were to do that we would probably need some type of annotation that indicated "approximate birth date based on proxy".

**Comment by danbri** [comment]
Thinking-out-loud ... is there any sense in which 'christening date' could be a synonym for a more general infant 'naming' event?

**Comment by DallanQ** [comment]
I think the key point with christening is that it is a "proxy" for birth because it typically happens within a few days (or maybe a year or two) of birth.  Baptism is likewise a proxy for birth.  So if you wanted to come up with a general term (which I don't think is necessary), then instead of focusing on the naming aspect, you ought to focus on the birth-proxy aspect.  You could use "birth-like" as your general term for example, or "near-birth".

**Comment by benwbrum** [comment]
As a developer for a site that's putting English parish registers online, I'm concerned about this.  For our own purposes, I don't believe we plan to indicate any difference between a baptism performed by antipedobaptist denominations and those performed by pedobaptist denominations -- among other issues the pedobaptist church theology I'm familiar with means that baptism of adult converts will be listed in the same sources as--and likely be indistinguishable from--infant baptisms performed in the same church.  Despite that, I'd be happy seeing "baptism" listed alongside other non-Christian life events (i.e. a Jewish bris) for which we have records as a "birth-like" or "near-birth" or "often-near-birth" event without aggregating them together.

**Comment by RobertGardner** [comment]
Again I'd like to emphasize that the "christening" field is not intended to capture a religious event. It is intended as a proxy for birth date. If the birth date is known, the chirstening field is not needed and perhaps should not be filled in. I think we need to do something to make this more clear. Any suggestions?

What about something like:
- remove christening
- on birthDate state that the date may be known or from a proxy to birth date, such as christening
- add an optional field birthDateProxy that can hold values like "christening", "baptism", etc.

Just a reminder that religious events such as baptism, bris, etc. can be captured in the "events" field.

**Comment by benwbrum** [comment]
My apologies -- I'd thought we were discussing HistoricalRecord, not Person.  I'm quite new to microformats, and will try to read a bit more before commenting next time.

**Comment by RobertGardner** [comment]
No problem. Hope I didn't sound testy -- didn't mean to and certainly don't want to drive you away or stifle comments. There is another discussion going on about events in HistoricalRecord. Your religious event comments would be quite germain there. DallanQ is leading that discussion, I haven't been involved in it.

**Comment by DallanQ** [comment]
That discussion RobertGardner refers to is here: https://github.com/historical-data/schema/issues/34  We don't have a separate "bris" event name; perhaps we should.  We'd welcome your comments.

**Comment by danbri** [comment]
Would 'approximate birth date' be a reasonably vague but useful substitute?

**Comment by DallanQ** [comment]
I wouldn't be against using "approximate birth date"; I'm just not sure it's necessary.

How about the following alternative?  We remove the christening property from the Person element.  If you don't have a birth event but do have a near-birth event (christening, baptism, bris, etc.), you use that event for the Person.birth property.  The name of that event (found in Person.birth.name) designates the type of event that is being used to provide birth information.  Now search-engines get what they want: exact or approximate birth information, people can use whatever exact or near-birth event they choose for the "birth" event, and the type of event used is recorded in the meta-data.  Similarly for burial and marriage (I could use a Marriage Banns event if I didn't have an exact marriage date for the marriage property).

**Comment by RobertGardner** [comment]
@DallanQ I like that. It's similar in spirit to my proposal but simpler. I assume that we would put the christening date in the Person.birthDate field, annotated to mark it as approximate (in whatever way schema.org decides to support approximate dates).

If there are no objections, I'll make the change, which basically is simply removing the christening field.

**Comment by DallanQ** [comment]
Sound good.  If you remove christening you should probably remove burial as well.
